merge_protections:
  - name: ALWAYS_ALLOW_CONTROL_61A4
    if: true
    success_conditions: true

merge_protections_settings:
  auto_merge_conditions:
    - mergify-configuration-changed

pull_request_rules:
  - name: BASE_CONFIG_RULE_61A4
    conditions:
      - base = main
    actions:
      comment:
        message: BASE_CONFIG_MARKER_61A4
