name: VM1 Mergify Queue Label Copier

on:
  pull_request_target:
    types:
      - opened

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  copier:
    runs-on: ubuntu-latest
    steps:
      - name: Copy trusted queue labels
        uses: Mergifyio/gha-mergify-merge-queue-labels-copier@v6
        with:
          labels: vm1-trusted-automerge
          token: ${{ github.token }}
